<script lang="ts">
  import { onMount } from 'svelte';
  import QRCode from 'qrcode';
  import { downloadRecoveryKit, getDeviceId, provisionFirstDevice, restoreDeviceFromRecovery, unlockDevice } from '$lib/keyStore';
  import { approvePairingCode, createPairingRequest, waitForPairing, type PairingSession } from '$lib/devicePairing';
  import { RelayClient, clearRelaySession, defaultRelayEndpoint, loadRelaySession, saveRelayEndpoint, saveRelaySession, type RelaySession } from '$lib/relayClient';

  export interface VaultReady { ownerId:string;masterKey:Uint8Array<ArrayBuffer>;session:RelaySession }
  let {onReady,onSignedOut}:{onReady:(vault:VaultReady)=>void|Promise<void>;onSignedOut?:()=>void|Promise<void>}=$props();
  type View='loading'|'connect'|'setup'|'choose'|'pairing'|'recovery-confirm'|'ready';
  let view=$state<View>('loading'),endpoint=$state(''),setupToken=$state(''),error=$state<string|null>(null),busy=$state(false),recoverySaved=$state(false),recoveryKit=$state(''),pairing=$state<PairingSession|null>(null),pairingQr=$state(''),pairingCode=$state(''),notice=$state<string|null>(null),menu=$state(false);
  let activeKey=$state<Uint8Array<ArrayBuffer>|null>(null),activeSession=$state<RelaySession|null>(null),abort:AbortController|null=null;

  onMount(()=>{endpoint=defaultRelayEndpoint();void boot();return()=>abort?.abort()});
  async function ready(session:RelaySession,key:Uint8Array<ArrayBuffer>){activeSession=session;activeKey=key;view='ready';await onReady({ownerId:session.instanceId,masterKey:key,session})}
  async function boot(){try{const session=loadRelaySession();const key=await unlockDevice();if(session&&key){await new RelayClient(session.endpoint,session.credential).vault();endpoint=session.endpoint;await ready(session,key);return}view='connect'}catch(e){error=e instanceof Error?e.message:String(e);view='connect'}}
  async function connect(){busy=true;error=null;try{saveRelayEndpoint(endpoint);const status=await new RelayClient(endpoint).status();view=status.initialized?'choose':'setup'}catch(e){error=e instanceof Error?e.message:String(e)}finally{busy=false}}
  async function claim(){busy=true;error=null;try{const deviceId=getDeviceId();const result=await new RelayClient(endpoint).claimSetup(setupToken,deviceId,navigator.userAgent.slice(0,100));setupToken='';const session={endpoint,instanceId:result.instanceId,deviceId,credential:result.deviceCredential};saveRelaySession(session);const existing=await unlockDevice();if(existing){await ready(session,existing)}else{const provisioned=await provisionFirstDevice();recoveryKit=provisioned.recoveryKit;activeKey=provisioned.masterKey;activeSession=session;view='recovery-confirm'}}catch(e){error=e instanceof Error?e.message:String(e)}finally{busy=false}}
  async function startPairing(){busy=true;error=null;try{pairing=await createPairingRequest(endpoint);pairingQr=await QRCode.toDataURL(JSON.stringify({type:'unkeep-pair',endpoint,code:pairing.code}));view='pairing';abort=new AbortController();const result=await waitForPairing(pairing,abort.signal);await ready(result.session,result.masterKey)}catch(e){if((e as Error).name!=='AbortError')error=e instanceof Error?e.message:String(e)}finally{busy=false}}
  async function restore(file:File){busy=true;error=null;try{const key=await restoreDeviceFromRecovery(await file.text());activeKey=key;notice='Key restored. Approve this device from an existing device to receive server access.';await startPairing()}catch(e){error=e instanceof Error?e.message:String(e)}finally{busy=false}}
  async function approve(){if(!activeSession||!activeKey)return;busy=true;error=null;try{await approvePairingCode(activeSession,pairingCode,activeKey);notice='Device approved';pairingCode=''}catch(e){error=e instanceof Error?e.message:String(e)}finally{busy=false}}
  async function finishRecovery(){if(!recoverySaved||!activeSession||!activeKey)return;await ready(activeSession,activeKey)}
  async function disconnect(){clearRelaySession();activeKey=null;activeSession=null;menu=false;await onSignedOut?.();view='connect'}
</script>

{#if view==='ready'}
  <div class="fixed right-2 top-[calc(0.875rem+env(safe-area-inset-top))] z-50 sm:right-3"><button class="rounded-full p-2 text-on-surface-muted hover:bg-surface-dim hover:text-on-surface" aria-label="Device menu" onclick={()=>menu=!menu}><svg class="h-5 w-5" fill="currentColor" viewBox="0 0 20 20"><path d="M10 6a2 2 0 110-4 2 2 0 010 4zm0 6a2 2 0 110-4 2 2 0 010 4zm0 6a2 2 0 110-4 2 2 0 010 4z"/></svg></button>{#if menu}<div class="absolute right-0 mt-2 w-72 max-w-[calc(100vw-1rem)] rounded-xl border border-border bg-surface p-4 shadow-xl"><p class="truncate text-sm">{activeSession?.endpoint}</p><form class="mt-3 flex gap-2" onsubmit={e=>{e.preventDefault();void approve()}}><input class="min-w-0 flex-1 rounded border border-border bg-surface px-2" placeholder="PAIR CODE" bind:value={pairingCode}/><button class="rounded bg-primary px-2 py-1 text-on-primary">Approve</button></form>{#if notice}<p class="mt-2 text-xs text-primary">{notice}</p>{/if}{#if error}<p class="mt-2 text-xs text-danger">{error}</p>{/if}<button class="mt-3 text-sm text-on-surface-muted" onclick={disconnect}>Disconnect this device</button></div>{/if}</div>
{:else}
  <main class="grid min-h-dvh place-items-center bg-surface-dim p-4"><section class="w-full max-w-md rounded-2xl border border-border bg-surface p-6 shadow-lg">
    <div class="mb-5 flex items-center gap-3"><img src="/icon.svg" alt="" class="h-12 w-12"/><div><h1 class="text-2xl font-semibold">UnKeep</h1><p class="text-sm text-on-surface-muted">Your notes. Your storage.</p></div></div>
    {#if view==='loading'}<p>Opening your vault…</p>
    {:else if view==='connect'}<form class="grid gap-3" onsubmit={e=>{e.preventDefault();void connect()}}><label class="grid gap-1 text-sm">Sync server<input class="rounded-lg border border-border bg-surface px-3 py-2" type="url" bind:value={endpoint} required/></label><button class="rounded-lg bg-primary px-4 py-2 text-on-primary" disabled={busy}>Connect</button></form>
    {:else if view==='setup'}<form class="grid gap-3" onsubmit={e=>{e.preventDefault();void claim()}}><p class="text-sm text-on-surface-muted">This is a new UnKeep server. Enter its one-time setup token.</p><input class="rounded-lg border border-border bg-surface px-3 py-2" type="password" autocomplete="off" bind:value={setupToken} required/><button class="rounded-lg bg-primary px-4 py-2 text-on-primary" disabled={busy}>Create vault</button></form>
    {:else if view==='choose'}<div class="grid gap-3"><p class="text-sm text-on-surface-muted">Connect this device to your encrypted vault.</p><button class="rounded-lg bg-primary px-4 py-2 text-on-primary" onclick={()=>void startPairing()} disabled={busy}>Pair with another device</button><label class="cursor-pointer rounded-lg border border-border px-4 py-2 text-center">Restore recovery kit<input class="hidden" type="file" accept="application/json" onchange={e=>{const f=e.currentTarget.files?.[0];if(f)void restore(f)}}/></label></div>
    {:else if view==='pairing'}<div class="text-center"><p>On an unlocked device, approve this code:</p><p class="my-3 font-mono text-2xl tracking-widest">{pairing?.code}</p>{#if pairingQr}<img class="mx-auto h-40 w-40" src={pairingQr} alt="Pairing QR code"/>{/if}<p class="mt-3 text-sm text-on-surface-muted">Waiting for approval…</p></div>
    {:else if view==='recovery-confirm'}<div class="grid gap-3"><h2 class="font-semibold">Save your recovery kit</h2><p class="text-sm text-on-surface-muted">It is the only way to recover your encryption key if every paired device is lost.</p><button class="rounded-lg border border-border px-4 py-2" onclick={()=>{downloadRecoveryKit(recoveryKit);recoverySaved=true}}>Download recovery kit</button><label class="flex gap-2 text-sm"><input type="checkbox" bind:checked={recoverySaved}/>I saved it somewhere safe</label><button class="rounded-lg bg-primary px-4 py-2 text-on-primary disabled:opacity-50" disabled={!recoverySaved} onclick={()=>void finishRecovery()}>Open UnKeep</button></div>{/if}
    {#if error}<p class="mt-4 text-sm text-danger" role="alert">{error}</p>{/if}
  </section></main>
{/if}
